In [1]:
import numpy as np

### 1 - Create a 3x3 array that contains a diagonal of nines.

In [2]:
dig = np.diag([9,9,9])
print(dig)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


### 2- Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32  

In [3]:
a = np.array([1,2,3], float)
arr = np.arange(2, 33, 2).reshape(4, 4)
print(arr)

mean = np.mean(arr)
std = np.std(arr)
check = abs(arr-mean) < 0.5 * std 
result = arr[check]
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[14 16 18 20]


### 3- Create a 9x9 array that contains only zeros of type int.

In [4]:
a = np.zeros((9,9), dtype=int)
print(a)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]




### 4- Ask the user for a number n and create matrices n*n . 

In [5]:
x = int(input("enter number to build matrices : "))

arr = np.arange(1,x+1,1)*np.ones((x, x))
print(arr)